apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: luiz.rlemos345@gmail.com
    privateKeySecretRef:
      name: letsencrypt-test-key
    solvers:
    - http01:
        ingress:
          class: nginx