apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"  # Mesma StorageClass do PVC
  hostPath:
    path: "/mnt/data/rabbitmq"  # Caminho no nรณ do Kubernetes