FROM python:3.12.1-alpine3.19

RUN apk update
RUN apk upgrade
RUN apk add git

COPY . /app

WORKDIR app

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools wheel


ARG API_TOKEN
ENV API_TOKEN=${API_TOKEN}
ARG ENVIRONMENT
ENV ENVIRONMENT=${ENVIRONMENT}


ENV DATABASE_URL DATABASE_URL
ENV RABBITMQ_URL RABBITMQ_URL
ENV STARKBANK_PROJECT_ID STARKBANK_PROJECT_ID
ENV STARKBANK_USER_PRIVATE_KEY STARKBANK_USER_PRIVATE_KEY

RUN pip install -r requirements.txt

EXPOSE 80:80

ENV PYTHONPATH="/app:${PYTHONPATH}"